#!/bin/bash

echo "aerOS Refresh Script will now download required files" 
echo "aerOS will download 3GB+ worth of packages"
read -n 1 -r -s -p $'Press enter to continue...\n'
pacman -Syu base linux alsa-utils dconf amd-ucode arch-install-scripts archinstall b43-fwcutter base bind brltty broadcom-wl btrfs-progs clonezilla cloud-init cryptsetup darkhttpd ddrescue dhclient dhcpcd diffutils dmidecode dmraid dnsmasq dosfstools e2fsprogs edk2-shell efibootmgr espeakup ethtool exfatprogs f2fs-tools fatresize fsarchiver gnu-netcat gpart gpm gptfdisk grml-zsh-config grub hdparm hyperv intel-ucode irssi iw iwd jfsutils kitty-terminfo less lftp libfido2 libusb-compat linux linux-atm linux-firmware linux-firmware-marvell livecd-sounds lsscsi lvm2 lynx man-db man-pages mc mdadm memtest86+ memtest86+-efi mkinitcpio mkinitcpio-archiso mkinitcpio-nfs-utils modemmanager mtools nano nbd ndisc6 nfs-utils nilfs-utils nmap ntfs-3g nvme-cli open-iscsi open-vm-tools openconnect openssh openvpn partclone parted partimage pcsclite ppp pptpclient pv qemu-guest-agent refind reflector reiserfsprogs rp-pppoe rsync rxvt-unicode-terminfo screen sdparm sg3_utils smartmontools sof-firmware squashfs-tools sudo syslinux systemd-resolvconf tcpdump terminus-font testdisk tmux tpm2-tss udftools usb_modeswitch usbmuxd usbutils vim virtualbox-guest-utils-nox vpnc wireless-regdb wireless_tools wpa_supplicant zsh firefox libreoffice-fresh nano gnome gnome-disk-utility kdenlive gimp xorg-xinit neofetch networkmanager network-manager-applet system-config-printer foomatic-db foomatic-db-engine gutenprint gsfonts cups cups-pdf cups-filters sane skanlite simple-scan xf86-input-vmmouse xf86-input-synaptics xf86-input-libinput xf86-input-evdev mesa lib32-mesa vulkan-icd-loader lib32-vulkan-icd-loader xf86-video-fbdev xf86-video-vmware xf86-video-intel xf86-video-ati p7zip unrar unarchiver unzip nfs-utils cifs-utils alsa-utils pavucontrol xorg-server xorg-xinit xorg-xrandr xorg-xfontsel xorg-xlsfonts xorg-xkill networkmanager network-manager-applet xorg-xinput xorg-xwininfo kdeconnect sshfs plymouth os-prober noto-fonts noto-fonts-cjk cups calamares ckbcomp mkinitcpio-openswap --noconfirm --download
echo "All packages is downloaded, Start refresh?"
read -n 1 -r -s -p $'Press enter to continue...\n'
echo "NOTE: All installed packages and configs will be forever lost!"
echo "Are you sure you want to start refresh? If not press Ctrl + C, or close terminal Window"
read -n 1 -r -s -p $'Press enter to continue...\n'
echo "Enter your username: "
read user_name
systemctl disable gdm
rm -rf /${user_name}/.config --no-preserve-root
rm -rf /root/.config --no-preserve-root
pacman -Rns --noconfirm $(comm -23 <(pacman -Qq | sort) <(echo -e "networkmanager\npacman\nbase\nlinux\nlinux-firmware"))
pacman -Su base linux alsa-utils dconf amd-ucode arch-install-scripts archinstall b43-fwcutter base bind brltty broadcom-wl btrfs-progs clonezilla cloud-init cryptsetup darkhttpd ddrescue dhclient dhcpcd diffutils dmidecode dmraid dnsmasq dosfstools e2fsprogs edk2-shell efibootmgr espeakup ethtool exfatprogs f2fs-tools fatresize fsarchiver gnu-netcat gpart gpm gptfdisk grml-zsh-config grub hdparm hyperv intel-ucode irssi iw iwd jfsutils kitty-terminfo less lftp libfido2 libusb-compat linux linux-atm linux-firmware linux-firmware-marvell livecd-sounds lsscsi lvm2 lynx man-db man-pages mc mdadm memtest86+ memtest86+-efi mkinitcpio mkinitcpio-archiso mkinitcpio-nfs-utils modemmanager mtools nano nbd ndisc6 nfs-utils nilfs-utils nmap ntfs-3g nvme-cli open-iscsi open-vm-tools openconnect openssh openvpn partclone parted partimage pcsclite ppp pptpclient pv qemu-guest-agent refind reflector reiserfsprogs rp-pppoe rsync rxvt-unicode-terminfo screen sdparm sg3_utils smartmontools sof-firmware squashfs-tools sudo syslinux systemd-resolvconf tcpdump terminus-font testdisk tmux tpm2-tss udftools usb_modeswitch usbmuxd usbutils vim virtualbox-guest-utils-nox vpnc wireless-regdb wireless_tools wpa_supplicant zsh firefox libreoffice-fresh nano gnome gnome-disk-utility kdenlive gimp xorg-xinit neofetch networkmanager network-manager-applet system-config-printer foomatic-db foomatic-db-engine gutenprint gsfonts cups cups-pdf cups-filters sane skanlite simple-scan xf86-input-vmmouse xf86-input-synaptics xf86-input-libinput xf86-input-evdev mesa lib32-mesa vulkan-icd-loader lib32-vulkan-icd-loader xf86-video-fbdev xf86-video-vmware xf86-video-intel xf86-video-ati p7zip unrar unarchiver unzip nfs-utils cifs-utils alsa-utils pavucontrol xorg-server xorg-xinit xorg-xrandr xorg-xfontsel xorg-xlsfonts xorg-xkill networkmanager network-manager-applet xorg-xinput xorg-xwininfo kdeconnect sshfs plymouth os-prober noto-fonts noto-fonts-cjk cups calamares ckbcomp mkinitcpio-openswap --noconfirm
systemctl enable gdm
pacman -Sccccc --noconfirm
dconf reset -f /
echo "Refresh Done, Reboot required"


